version: 2
jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          name: Build and run iOS unit tests
          command: xcodebuild -project Switchboard.xcodeproj -scheme Switchboard -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7' -enableCodeCoverage YES test | xcpretty --test
      - run:
          name: Build and run iOS UI tests
          command: xcodebuild -project Switchboard.xcodeproj -scheme SwitchboardExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7' -enableCodeCoverage YES test | xcpretty --test
      - run:
          name: Build and run macOS tests
          command: xcodebuild -project Switchboard.xcodeproj -scheme Switchboard -sdk macosx -destination 'platform=OS X,arch=x86_64' -enableCodeCoverage YES test | xcpretty --test
      - run:
          name: Lint the pod
          command: pod lib lint --allow-warnings
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
